load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

#only one mediapipe_aar target can exist at a time!

#mediapipe_aar(
#    name = "mediapipe_hand_tracking",
#    calculators = ["//mediapipe/graphs/hand_tracking:mobile_calculators"],
#)

mediapipe_aar(
    name = "mediapipe_face_mesh_gpu",
    calculators = ["//mediapipe/graphs/face_mesh:mobile_calculators"],
)


#load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")
#
#mediapipe_aar(
#    name = "mediapipe_instant_motion_tracking",
#    calculators = ["//mediapipe/graphs/instant_motion_tracking:instant_motion_tracking_deps"],
#)
